# Generated by Django 3.1.5 on 2021-11-22 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_language', models.CharField(choices=[('FRE', 'French'), ('ESP', 'Spanish'), ('ZHO', 'Chinese')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PairsQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.questionbase')),
                ('mixed', models.BooleanField(default=False)),
                ('word_pairs', models.JSONField()),
            ],
            bases=('lessons.questionbase',),
        ),
        migrations.CreateModel(
            name='SentenceMCQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.questionbase')),
                ('native_language_sentence', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answer_options', models.JSONField()),
            ],
            bases=('lessons.questionbase',),
        ),
        migrations.CreateModel(
            name='TranslatePickWordsQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.questionbase')),
                ('native_language_sentence', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('word_options', models.JSONField()),
            ],
            bases=('lessons.questionbase',),
        ),
        migrations.CreateModel(
            name='VocabMCQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.questionbase')),
                ('vocab_word', models.CharField(max_length=40)),
                ('correct_answer', models.CharField(max_length=40)),
                ('incorrect_answer_options', models.JSONField()),
            ],
            bases=('lessons.questionbase',),
        ),
        migrations.CreateModel(
            name='WriteSentenceQuestion',
            fields=[
                ('questionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.questionbase')),
                ('native_language_sentence', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
            bases=('lessons.questionbase',),
        ),
        migrations.AddField(
            model_name='questionbase',
            name='subjects',
            field=models.ManyToManyField(to='lessons.Subject'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='lessons.QuestionBase')),
                ('subjects', models.ManyToManyField(to='lessons.Subject')),
            ],
        ),
    ]
