# Generated by Django 3.1.5 on 2021-12-07 20:29

from django.db import migrations, models
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatepickwordsquestion',
            name='word_options',
        ),
        migrations.AddField(
            model_name='translatepickwordsquestion',
            name='incorrect_words',
            field=models.JSONField(default=('mujer',), validators=[lessons.models.validate_pick_words_JSON]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairsquestion',
            name='word_pairs',
            field=models.JSONField(validators=[lessons.models.validate_word_pairs_JSON]),
        ),
        migrations.AlterField(
            model_name='sentencemcquestion',
            name='correct_answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sentencemcquestion',
            name='incorrect_answer_options',
            field=models.JSONField(validators=[lessons.models.validate_mc_JSON]),
        ),
        migrations.AlterField(
            model_name='sentencemcquestion',
            name='native_language_sentence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='translatepickwordsquestion',
            name='correct_answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='translatepickwordsquestion',
            name='native_language_sentence',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vocabmcquestion',
            name='correct_answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vocabmcquestion',
            name='incorrect_answer_options',
            field=models.JSONField(validators=[lessons.models.validate_mc_JSON]),
        ),
        migrations.AlterField(
            model_name='vocabmcquestion',
            name='vocab_word',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='writesentencequestion',
            name='correct_answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='writesentencequestion',
            name='native_language_sentence',
            field=models.CharField(max_length=150),
        ),
    ]
