# Generated by Django 3.1.5 on 2023-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabmcquestion',
            name='incorrect_answer_options',
            field=models.ManyToManyField(help_text='Each multiple-choice question should have three options for incorrect answers', related_name='question_this_is_incorrect_option_for', to='lessons.VocabWord'),
        ),
    ]
