# Generated by Django 3.1.5 on 2023-07-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20230717_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabmcquestion',
            name='incorrect_answer_options',
            field=models.ManyToManyField(help_text='Question should have three options for incorrect answers', related_name='question_this_is_incorrect_option_for', to='lessons.VocabWord'),
        ),
    ]
