# Generated by Django 3.1.5 on 2022-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbase',
            name='question_language',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
