# Generated by Django 3.1.5 on 2022-01-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_lesson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questionbase',
            name='question_language',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_ID',
            field=models.CharField(default='lesson296297', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
