# Generated by Django 3.1.5 on 2022-04-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20220202_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievementblah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('points', models.SmallIntegerField()),
            ],
        ),
    ]
