# Generated by Django 3.1.5 on 2022-05-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_achievementblah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievementblah',
        ),
    ]
